# Generated by Django 2.2.2 on 2019-07-18 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CrawlerApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseUrlImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home_image', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='PageImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_image', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='PageUrl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='SubPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_page', models.CharField(max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='baseurl',
            name='image',
        ),
        migrations.RemoveField(
            model_name='baseurl',
            name='page',
        ),
        migrations.RemoveField(
            model_name='baseurl',
            name='sub_page',
        ),
        migrations.RemoveField(
            model_name='baseurl',
            name='sup_page_image',
        ),
    ]
