# Generated by Django 2.2.2 on 2019-07-20 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CrawlerApp', '0003_urldepth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urldepth',
            name='depth',
            field=models.IntegerField(),
        ),
    ]
